### ISSUE TITLE
Mobile Google Plus - C3 runtime - BlackScreen

### ISSUE THREAD

**Issue by klabundee** [Chadori/construct-master-collection#112]
## Request Type
This is a **Bug Report**.

## Describe the bug
When using Mobile Google Plus it breaks the app when running on mobile.
Even without actions set.. just after add the plugin, it will not work anymore.
The app still works on browser preview.
It does not happen when running C2 runtime.

## Reproducible .c3p or .capx
_Insert the project file here._

## Steps to Reproduce
1. Create a new project
2. Add Mobile Google Plus
3. Export to debug APK
4. Install the apk
5. Run it -> BlackScreen.

## Expected behavior
The project should at least start without blackscreen as we have no actions set to the plugin..

## Screenshots
Sent to chadori's discord.

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
r159

**Comment by Chadori** [comment]
Alright. This will be fixed in a few hours.

**Comment by Chadori** [comment]
Will schedule it.

**Comment by Chadori** [comment]
It was a false alarm, as said by the reporter. **Closing**!
Though, new progress has been made into the plugin, codes were refined and polished.

New **Mobile GooglePlus** version **1.1.1.1**.

**Comment by Chadori** [comment]
The debug tools found an error on the **1.1.0.0** version. Removing the **False Tag**, although this report will remain closed since it has been resolved.
