### ISSUE TITLE
IAP not working

### ISSUE THREAD

**Issue by ghost** [Chadori/construct-master-collection#118]
## Request Type
This is a **Bug Report**.

## Describe the bug
When i enter first the layout this error comes up --> "invalid argument - productIds must be an array of strings". but when i close the layout and get in again this error disappears and i can purchase. I think this happens beacuse intializing starts before the installation of the products finished? I can may be wrong here. You told me i have to enable the store when Restore purchases finished. The second problem is here, when i leave the layout and enter the third time my store will not be enabled. Maybe because Restoring Purchases have been already done? I use phonegap for exporting.
The third problem i have is that the expression "MobileMasterIAP.recentPurchaseProductID" doesn`t work. Nothing happens if purchase succeded. You have to write down the productid (like in my second screenshot --> "pack3"). Maybe somebody got it to work and can help me here... Thanks!

## Screenshots
![G1](https://user-images.githubusercontent.com/54187911/63191634-45ffc580-c069-11e9-8f34-efdf201a2106.png)

![G2](https://user-images.githubusercontent.com/54187911/63191652-53b54b00-c069-11e9-972f-e7679108060b.png)

## Construct Editor
 - Construct 2

## Construct Runtime
 - Construct 2

 ## Construct 2 Version
Latest

**Comment by Chadori** [comment]
I really need a test project for this, and also an .apk with **debug-mode** - **on**, which also captures the error messages on the application side via textbox or text.
Cause, it's hard dealing which involves recreating stuffs I'm not sure would reproduce the issue.

I recommend you add the following:

- Minimal Project
- .apk / .ipa
- Steps to reproduce
- Product IDs
- Release status
- ErrorMessage display in the application.
- DebugMode : On

You can send them privately, but remember to reference this post.

Thanks.

**Comment by ghost** [comment]
Hi Chadori, can you may please use your own Android Sample capx in the documentation? I did everything like your documentation.. Release status is open Beta

**Comment by Chadori** [comment]
Okay, I just did.

-----

## 1st Initialization
![image](https://user-images.githubusercontent.com/31282960/63193366-e1139200-c09f-11e9-810d-debdd5846611.png)
**(Purchase)**
![image](https://user-images.githubusercontent.com/31282960/63193366-e1139200-c09f-11e9-810d-debdd5846611.png)

## 2nd Initialization
![image](https://user-images.githubusercontent.com/31282960/63193397-f25c9e80-c09f-11e9-8fa4-accd680c8b48.png)

## 3rd Initialization
**(Redundancy, to be absolute sure!)**
![image](https://user-images.githubusercontent.com/31282960/63193547-5d0dda00-c0a0-11e9-9458-ad13eddee3b9.png)
![image](https://user-images.githubusercontent.com/31282960/63193555-6008ca80-c0a0-11e9-9c4f-86a8119af974.png)
![image](https://user-images.githubusercontent.com/31282960/63193561-6303bb00-c0a0-11e9-8b24-d03606d79535.png)
**(MobileMasterIAP.recentPurchaseProductID)** returned at the last textarea, which is the **consumable**. You can see for yourself.

**Comment by Chadori** [comment]
@xh3moo As checked, it works fine. 

Will give you a bit time to respond before closing. Have a nice day.

**Comment by Chadori** [comment]
As the reporter agreed, it was just an event-making error of the project.

![image](https://user-images.githubusercontent.com/31282960/63194760-6cdaed80-c0a3-11e9-8173-d2dfc0dff14d.png)

The **wait** action causes the **installation** of **product-ids** to be delayed compared to the **initialization**. Hence, **initialization** happens with no **product-ids** installed.

-----

Since it's resolved, now **closing**, noted **false alarm**.
