### ISSUE TITLE
Mobile Master IAP : For Upgrade

### ISSUE THREAD

**Issue by Chadori** [Chadori/construct-master-collection#119]
## Request Type
**Feature Request**

## Information
**Upgrade plan for the Mobile Master IAP**. 

It has already been a year since the release of the in-app purchase plugin and it has been running stably for the past 8 months with no failure, although due to the advancing of tech, in-app purchase, subscriptions and the new Cordova versions coming out, it makes perfect sense to make a plugin refactor upgrade.

The original written code was made universal for both the **c2runtime** & **c3runtime** and as new features were added, the more complicated it became. This highly affected **c3runtime** since it shared the code with the **c2runtime**, in which it could have been improved by using dedicated code and ES6 features.

There are more improvements that can be made, but notably, the current **subscription** feature has no feature to determine if a subscription is:

- Active
- Cancelled
- or Refunded

,which is useful if ever you want to customize your subscription implementation.

These bring the opportunity to apply new features and solve some limitations.

**To-do list**
- Code refactor - make code readable and efficient. Especially for the c3runtime.
- Expressions for the 'purchase/subscription' status: **Active**, **Cancelled** or **Refunded** .
- Helper Conditions and Expressions.
- Other Status Expressions.
- Support for the **Cordova CLI** version, **8.1.1** or if soon possible, **9.0.0**.
- Improved Sample Project.
- Integration with the documentation website.

_For each feature done will be marked with a ✔️, ❌ for cancelled features and ⏸ for hold. The issue will be closed when all items in the to-do list are marked with one of the tag symbol, indicating resolve._

## Construct Editor
 - Construct 2
 - Construct 3

## Construct Runtime
 - Construct 2
 - Construct 3

**Comment by lumicreative** [comment]
Great to hear there are updates coming! Thanks!

**Comment by Chadori** [comment]
Finished, included in: https://github.com/Chadori/Construct-Master-Collection/issues/401
