### ISSUE TITLE
Automate the patch from the docs to the editor

### ISSUE THREAD

**Issue by lumicreative** [Chadori/construct-master-collection#120]
## Request Type
**Feature Request**

## Information
From Chadori: "@Lumicreative.com You can use the docs for reference. But you can file a feature request on #tracking to automate the patch from the docs to the editor, so I can make a schedule for it."

## Feature Demo
Not sure I understand what Chadori was referring to, but the request is to automate the patch from the docs to the editor.

## Construct Editor
 - Construct 2
 - Construct 3

## Construct Runtime
 - Construct 2
 - Construct 3

## Additional Info
None

**Comment by Chadori** [comment]
@lumicreative thanks for reporting. I just decided to work on it immediately.

The automation patch update is available on the **Discord Server**'s `#next-release` channel. The official release should be on the next release, **7.0.0**.

-----

**Mobile Master Ads** :: (1.2.1.1) - Construct 3 Editor additions and changes:
+ **Admob SDK** : Added the Configuration properties group.
+ **Admob SDK** : Added the toggle to enable specifying the Play Services Version to support the **C3 Google Play** plugin or any other purposes.
+ **Admob SDK** : Pre-added the `11.0.6` Play Services version default to the `Play Services Version` property to support the **C3 Google Play** plugin.
+ Configuration Automation for the **Admob SDK**, for the **Construct 3** Editor.
