### ISSUE TITLE
Firebase Plugin doesn't load again

### ISSUE THREAD

**Issue by vundurty** [Chadori/construct-master-collection#142]
## Request Type
This is a **Bug Report**.

## Describe the bug
This is in reference to #135
The bug still persists. 

It doesn't work for me. I tired with your test credentials from the sample C3P, it's still the same. It doesn't load.

## Reproducible .c3p or .capx
[FirebaseTest.zip](https://github.com/ChadoriRebornXD/Construct-Master-Collection/files/3693630/FirebaseTest.zip)

## Steps to Reproduce
1. Preview the project
2. A blank screen will appear
3. Check the console for errors
4. 

## Expected behavior
Project should load and Authentication should work

## Screenshots
![Screenshot 2019-10-06 00 57 33](https://user-images.githubusercontent.com/22640025/66259860-6bd95900-e7d4-11e9-804a-a320e676636c.png)

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
 **164.3**

 ## Construct 2 Version
 **NA**

## Additional Info
[FirebaseTest.zip](https://github.com/ChadoriRebornXD/Construct-Master-Collection/files/3693629/FirebaseTest.zip)

**Comment by Chadori** [comment]
Hi, this isn't a bug, **worker** is an experimental feature, hence not supported.
You can turn that off through this option:
![image](https://user-images.githubusercontent.com/31282960/66264278-dae69a00-e834-11e9-842f-cf9e6e2aed73.png)

**Comment by Chadori** [comment]
Also, as mentioned here: https://github.com/ChadoriRebornXD/Construct-Master-Collection/issues/135
Please use your own Firebase Credentials, I don't recall adding my own credentials there, hence it might just be a leftover credential from Construct 2 that's no longer working.

Here's a tutorial I've found that could help you:
https://shatter-box.com/knowledgebase/firebase-sync-data-with-your-construct-2-game/

**Comment by vundurty** [comment]
I didn't know this. This was a miss from my end. Thanks alot for explaining. It works now.
