### ISSUE TITLE
Mobile GooglePlus - BlackScreen

### ISSUE THREAD

**Issue by vundurty** [Chadori/construct-master-collection#165]
## Request Type
This is a **Bug Report**.

## Describe the bug
Getting a black screen when adding the MobileGooglePlus Plugin. I'm not sure if I missed anything but I made sure I followed all the documentation from the plugin website for implementation.

I have created credentials on Google API Console.

Added them to the project (both Web client ID and reversed ID)

This happens only on mobile not desktop.

## Expected behavior
App should be launched without any issues and proceed with login.

## Screenshots
Error from console

![Screenshot 2019-10-23 02 39 45](https://user-images.githubusercontent.com/22640025/67333816-d281a500-f53e-11e9-8d89-246581c28a29.png)

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
 **171.3**

## Additional Info
Please let me know if you need any further information.

**Comment by Chadori** [comment]
The Mobile Google Plus was just recently tested and worked well, it might be other things going around there.

If you are sure this is a bug, please send your project with the credentials to support@constructcollection.com.

Including a debug .apk. please.

The debug error doesn't seem to reference the Mobile GooglePlus.

**Comment by vundurty** [comment]
Thanks for looking into this.

I'm not sure whether it went wrong but it happens only if this plugin is added.

I have sent the files to the mentioned email ID.

**Comment by Chadori** [comment]
Alright, I've received the files. Give me a few hours before I get to look at it. Thanks.

**Comment by vundurty** [comment]
@ChadoriRebornXD 

Any update on this?

**Comment by Chadori** [comment]
**Closed** due to **time constraints**, apologies. Although, we have a better support now, either through the website: https://www.constructcollection.com/ or support@constructcollection.com.

Thank you!
