### ISSUE TITLE
GFX :: Set Style function typo causing unintended effects, including failing to set.

### ISSUE THREAD

**Issue by Chadori** [Chadori/construct-master-collection#191]
## Request Type
This is a **Bug Report**.

## Describe the bug
**GFX** :: Set Style function typo causing unintended effects, including failing to set.

## Steps to Reproduce
Steps to reproduce the behavior: **[Sample situation]**
1. Preset **Style** to **Automatic** from the properties.
2. Then, set **Style** to **Manual**.
3. Set **GFX Quality** will fail to run.

## Possible Cause
```
        SetStyle(toggle)
        {
            if (this._style !== toggle)
            {
                this._style = toggle;

                if (this.style === 0)
                {
                    this.SetAutomatic();
                }
                else
                {
                    this.SetManual();
                }
            }
        }
```

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

## Additional Info
Fix the incorrectly called methods, although testing is needed to confirm.

**Comment by Chadori** [comment]
Code confirmed to be the issue. **Completed**, now closing.
GFX : **1.0.1.0** - Patch version.

**Comment by ChadoriRebornXD** [comment]
**Patch available** on the **Discord Community**, under `next-release`.

**Comment by Chadori** [comment]
**Patch available** in the **Discord Community**, under `next-release`.
