### ISSUE TITLE
GFX : Failed to do a relative Layout Scale during automated or manual optimization.

### ISSUE THREAD

**Issue by Chadori** [Chadori/construct-master-collection#200]
## Request Type
This is a **Bug Report**.

## Describe the bug
**GFX** : Failed to do a relative Layout Scale during automated or manual optimization.

## Reason
Didn't properly record the `user defined` scale during previously specified conditions.

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

## Additional Info
New version :: **GFX : 1.0.1.1**

**Comment by ChadoriRebornXD** [comment]
**Implemented**, now closing.

**Comment by Chadori** [comment]
**Fixed**, now closed.
