### ISSUE TITLE
Vungle mediator crashes android build

### ISSUE THREAD

**Issue by trueicecold** [Chadori/construct-master-collection#214]
When using Master Ads with Vungle mediator, cordova build crashes.

1. Add Master Ads and fill in the details
2. Add Vungle Mediator and fell in the details
3. Export to cordova project
4. Try to build it using cordova cli

## Expected behavior
A build should be generated successfully

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
r182.2 stable

## Additional Info
Seems an issue with the multidex plugin dependency, which tries to edit AndroidManifest from the old location (platforms/android/AndroidManifest.xml) rather than app/src/main/AndroidManifest.xml

**Comment by Chadori** [comment]
Would fix, but there is an incoming dedicated Ads mediation network. I think the focus should be there instead. So, just going to mark this **won't fix**.
