### ISSUE TITLE
MobileOneSignal.UserID does not return userID

### ISSUE THREAD

**Issue by Boulerzzz** [Chadori/construct-master-collection#218]
## Request Type
This is a **Bug Report**.

## Describe the bug
The MobileOneSignal.UserID does not return the userid.

## Reproducible .c3p or .capx
[test.zip](https://github.com/ChadoriRebornXD/Construct-Master-Collection/files/4181578/test.zip)

## Steps to Reproduce
1.  Create a OneSignal app
2.  Add MobileOneSignal plugin to a project
3.  Fill in the App ID
4.  Build the app and try to get the ID by using the MobileOneSignal.UserID expression

## Expected behavior
To get the OneSignal ID

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
r185

**Comment by Chadori** [comment]
Needs an .apk / ios application that shows that it doesn't return the **user id**.

**Comment by Boulerzzz** [comment]
[tester.android.debug.apk.zip](https://github.com/ChadoriRebornXD/Construct-Master-Collection/files/4181716/tester.android.debug.apk.zip)

Edit: Don't know how to really show it doesn't return the user id. It's an apk with only 2 events.
![Events](https://user-images.githubusercontent.com/34767801/74166949-228c9080-4c30-11ea-8364-c77b53bc8f4f.PNG)

**Comment by Chadori** [comment]
**Not a bug**, you set all on **Manual** mode, but didn't manually retrieve the current **Permission Subscription State**.

Marking as **False**, please read and use the **documentation** as a guide, don't assume how it works without trying on the documentation projects first.

**Comment by Chadori** [comment]
![image](https://user-images.githubusercontent.com/31282960/74167737-9f852d80-4c63-11ea-9aa0-3dfdfb23ce56.png)

Here's how it shows on my end. It shows the **User ID** without a problem.

**Comment by Boulerzzz** [comment]
Manual mode or not. It still returns the same error when trying the post notification action.

![ScreenShot](https://user-images.githubusercontent.com/34767801/74170701-04c22a00-4c36-11ea-9c13-0a62b8c089b3.jpeg)

**Comment by Chadori** [comment]
@Boulerzzz this one is closed. Could you move this to the appropriate topic and I'll reopen that topic. Thanks.

**Comment by Chadori** [comment]
Resolved and isn't a **bug**.
**Locking** to prevent getting replied with unrelated topics.
Please move further replies to an appropriate topic.
