### ISSUE TITLE
MobileOneSignal Post notification returns error

### ISSUE THREAD

**Issue by Boulerzzz** [Chadori/construct-master-collection#219]
## Request Type
This is a **Bug Report**.

## Describe the bug
App fails to post a notification.

## Steps to Reproduce
1.  Create a post notification action/function
2.  Call the function

## Expected behavior
Expect

 to send notification

## Screenshots
![PostNotification](https://user-images.githubusercontent.com/34767801/74163424-09cdac00-4c2b-11ea-82d4-da85dd3add5f.PNG)

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
r185

## Additional Info
Could be related to my other post earlier. 
Debug APK shows the following error when attempting to send.

On Post Notification Failure
The JSON data string of the (error) below is retrievable through the expression "PostNotificationData"
Invalid action

**Comment by Chadori** [comment]
Requires error logs, since this could just be a misconfiguration.

**Comment by Chadori** [comment]
As mentioned here: https://github.com/ChadoriRebornXD/Construct-Master-Collection/issues/218

This is **not a bug**, this is a **misconfiguration**.

**Comment by Boulerzzz** [comment]
I get this error in the test project as well.

![ScreenShot](https://user-images.githubusercontent.com/34767801/74175131-dba59780-4c3d-11ea-9528-3194e64b3a9c.jpeg)

**Comment by Chadori** [comment]
Looks like a documentation fault of mine.
Add this at the end of your JavaScript event:
```
localVars.ParameterJSON = JSON.stringify(localVars.ParameterJSON);
```
See if that solves it.

**Comment by Boulerzzz** [comment]
Unfortunately that did not solve it for me.

`const userID = localVars.UserID;

localVars.ParameterJSON = 
{ "contents": 
	{"en": "message body"},
  "include_player_ids": 
	[userID]
};

localVars.ParameterJSON = JSON.stringify(localVars.ParameterJSON);`

I still get the same error message.

**Comment by Chadori** [comment]
Just to be sure, could you specify the exact error message?

**Comment by Boulerzzz** [comment]
On Post Notification Failure

Received 'post Notification' error data in JSON string:

"Invalid action"

I can send notifications from OneSignal website without any issues. My only problem is when I want to create them using the post notification action. :(

**Comment by Chadori** [comment]
I uploaded a **candidate fix; new addon version** at the [Discord Server](https://discordapp.com/invite/eS3HK88), in the `beta-release` channel. 
Check if that works, hopefully it will now.

**Comment by Boulerzzz** [comment]
Thanks.
I tried the new version and it does not send notifications successfully. One thing I noticed with the new version of the plugin was that the post notification action does not trigger neither "On Post Notification Success" nor "On Post Notification Failure".

**Comment by Boulerzzz** [comment]
![Capture](https://user-images.githubusercontent.com/34767801/74232491-96cb4080-4cd1-11ea-954f-87a43c913bd4.PNG)

c3runtime.js:1057 Uncaught (in promise) SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at CV_MobileOneSignalInstance.PostNotification (c3runtime.js:1057)
    at CV_MobileOneSignalInstance.PostNotification (c3runtime.js:1404)
    at C3.Action.Run (c3runtime.js:328)
    at C3.EventBlock._RunActions_Fast (c3runtime.js:304)
    at C3.EventBlock._RunAndBlock (c3runtime.js:304)
    at C3.EventBlock.Run (c3runtime.js:304)
    at C3.EventBlock._RunSubEvents_Fast (c3runtime.js:304)
    at C3.EventBlock._RunSubEvents (c3runtime.js:304)
    at C3.EventBlock._RunAndBlock (c3runtime.js:304)

I get this message when I debug. Not sure if its helpful.

**Comment by Chadori** [comment]
Yeah, that's helpful.
Give me time, and I'll look this up myself and fix it.

**Comment by Chadori** [comment]
Sorry it took a while. 

It has been tough to diagnose due to it being a bug error from both the addon and the Scripting runtime having issues being assigned with `null` values.

Now the addon automatically converts the type values. So, it now has a fallback value of an empty string.
-----

![image](https://user-images.githubusercontent.com/31282960/78640814-f2393980-78e2-11ea-8ec3-460060d75bc4.png)

**Mobile OneSignal :: 1.1.1.0** 
**Fixed**, now closed.

**Comment by Chadori** [comment]
Sorry it took a while. 

It has been tough to diagnose due to it being a bug error from both the addon and the Scripting runtime having issues being assigned with `null` values.

Now the addon automatically converts the type values. So, it now has a fallback value of an empty string.

-----

![image](https://user-images.githubusercontent.com/31282960/78640814-f2393980-78e2-11ea-8ec3-460060d75bc4.png)

**Mobile OneSignal :: 1.1.1.0** 
**Fixed**, now closed.

**Comment by Boulerzzz** [comment]
Woohoo thanks! 👍 
I'll try to set it up later this week. Do we still use the same method shown in the documentation project? :)

**Comment by Chadori** [comment]
You are welcome.
There's a slight change. I've also added it in the `#next-release` channel.

**Comment by Boulerzzz** [comment]
Just did a quick test and it works perfectly now!
Just want to say thank you for taking the time to solve this. :) :]
