### ISSUE TITLE
Mobile GooglePlus - Sync the Play Services Version with Construct 3's plugins.

### ISSUE THREAD

**Issue by Chadori** [Chadori/construct-master-collection#220]
## Request Type
Either a **Feature Request**

## Information
Sync the Play Services Version with Construct 3 Cordova plugins using Play Services.

## Construct Editor
 - Construct 2
 - Construct 3

## Construct Runtime
 - Construct 2
 - Construct 3

## Additional Info
**Mobile GooglePlus :: 1.1.1.5** - Synced the Play Services Version with Construct 3 Cordova plugins using Play Services.

**Comment by ChadoriRebornXD** [comment]
**Trial run** - in progress.

**Comment by ChadoriRebornXD** [comment]
**Trial run** - currently testing if it's working alright with the C3 build service.

**Comment by Chadori** [comment]
**Trial run** - for testing with the **C3 build service**.

**Comment by Chadori** [comment]
**Awaiting:** https://github.com/Scirra/Construct-3-bugs/issues/3643.

**Comment by Chadori** [comment]
**Implemented**, now closed.
