### ISSUE TITLE
[Playfab API Plugin] Client profile data properties: change Included "Values to Date in UDS" but ServerResponse does not return results of "Values to Date in UDS"

### ISSUE THREAD

**Issue by tuzke** [Chadori/construct-master-collection#221]
## Request Type
[Playfab API Plugin] Client profile data properties: change Included "Values to Date in UDS" but ServerResponse does not return results of "Values to Date in UDS" 
(Client Profile Options in playfab have full check of authority)

## Describe the bug
[Playfab API Plugin] Client profile data properties: change Included "Values to Date in UDS" but ServerResponse does not return results of "Values to Date in UDS"
(Client Profile Options in playfab have full check of authority)

## Reproducible .c3p or .capx
_Insert the project file here._

## Steps to Reproduce
[Playfab API Plugin] Client profile data properties: change Included "Values to Date in UDS" but ServerResponse does not return results of "Values to Date in UDS"

## Construct Editor

 - Construct 3

## Construct Runtime

 - Construct 3

**Comment by Chadori** [comment]
Hi, as per tested, it seems to be working just fine. Are you sure you have set your **PlayFab Console** and **PlayFab API** correctly?

![image](https://user-images.githubusercontent.com/31282960/74229369-3225db00-4cfd-11ea-920d-68a254aa6a77.png)

**Comment by tuzke** [comment]
The value of "Values to Date" is returned but the value of "Values to Date in UDS" is not

**Comment by Chadori** [comment]
It's inside the **Values To Date**, it's an array.
![image](https://user-images.githubusercontent.com/31282960/74229624-bbd5a880-4cfd-11ea-8c7d-e56c53c44b3f.png)

**Comment by Chadori** [comment]
Closed as **false alarm**, as it's not a bug. It's working alright as tested.

**Comment by Chadori** [comment]
For documentation purposes, as tested, `TotalValueToDateInUSD` shows:

![image](https://user-images.githubusercontent.com/31282960/74232196-410f8c00-4d03-11ea-9c46-dfb8e16a31a4.png)

**It's working alright.** Doesn't seem to be any bug or fault in the code.

But, for some reason, the current user's case, it doesn't. 
For the sake of documentation on resolving this in the future, this will remain open for a while or once the cause has been found, to give chance for a solution to come up.

**Comment by Chadori** [comment]
The user mentioned getting the profile from the **Leaderboards (Legacy)** rather than the **Player Manager**. Where I've found a reference typo.

**Addons with bug**:
- Leaderboards (Legacy)
- Leaderboards

**Schedule** for future fix.
-----
**Note:** Check other PlayFab addons with **Profile Constraints** if containing the typo.

**Comment by Chadori** [comment]
**Fixed**, now closed.

**Comment by Chadori** [comment]
The release should be available on **10.0**, but in the meantime, you can get the update from the [Discord Community](https://discordapp.com/invite/eS3HK88), in the `#next-release` channel.
