### ISSUE TITLE
Messlek - Enhance Reward Video Does Not Grant Reward

### ISSUE THREAD

**Issue by klssem** [Chadori/construct-master-collection#230]
## Request Type
This is a **Bug Report**.

## Describe the bug
The enhance addon does not grant reward after the reward video completes

## Reproducible .c3p or .capx
_Insert the project file here._

## Steps to Reproduce
1. In the start page click the key icon
2. Watch the reward add until it ends
3. The number next to the key icon should increase
4. 

## Expected behavior
After the reward video has been watched the number next to the key should increase

## Screenshots
![image](https://user-images.githubusercontent.com/62447794/77206805-e4ec1480-6ac5-11ea-8d45-083326facc5b.png)
![image](https://user-images.githubusercontent.com/62447794/77206836-f46b5d80-6ac5-11ea-810e-d524df48cf5c.png)

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
 **The Construct 3 Version**

 ## Construct 2 Version
 **N/A**

## Additional Info
I am using Unity ads and KiDoz ads through Enhance.co
The number of keys does increase if I use the following event without the reward video:
On tap gesture on key > System- set key to key + 1

**Comment by Chadori** [comment]
Hi, sorry for the late reply. But I think I have fixed it now. _(I can't test fully without a reproducible project.)_
Let me know if you still get any issues, then I'll work on it immediately.

**Mobile Enhance :: 1.1.1.0** - Fixed callback triggers not firing properly.

**Comment by Chadori** [comment]
**Fixed**, now closed.

**Comment by Chadori** [comment]
If you want to use the fix now, it's on the [Discord Community](https://discordapp.com/invite/eS3HK88), in the `#next-release` channel.
