### ISSUE TITLE
[Mobile Review] “This build is missing export compliance information.”

### ISSUE THREAD

**Issue by SalmanShhh** [Chadori/construct-master-collection#232]
## Request Type
This is a **Bug Report**.

## Describe the bug
could be possible related to this [](https://stackoverflow.com/questions/51908451/this-build-is-missing-export-compliance-information) . 

## Reproducible .c3p or .capx
_Insert the project file here._

## Steps to Reproduce
1.  export a game asking for a review on mobile
2. upload to testflight/app store

## Expected behavior
not expecting this 
<img width="451" alt="Screenshot 2020-03-22 at 00 40 20" src="https://user-images.githubusercontent.com/21278459/77239836-e822f580-6bd6-11ea-9378-39a03300252d.png">

## Construct Editor
 - Construct 2
 - Construct 3

## Construct Runtime
 - Construct 2
 - Construct 3

 ## Construct 3 Version 
 **The Construct 3 Version**

 ## Construct 2 Version
 **The Construct 2 Version**

**Comment by Chadori** [comment]
Should be easy to implement, I should be able to release a patch soon. Thanks.
Until then, here's the workaround: https://github.com/Scirra/Construct-3-bugs/issues/3719

**Comment by Chadori** [comment]
Should be easy to implement, I should be able to release a patch soon. Thanks.
Until then, here's the workaround: 
```XML
<config-file target="*-Info.plist" parent="ITSAppUsesNonExemptEncryption">
   <false/>
</config-file>
```
Paste this into your `config.xml`, between `platform name="ios>` and `/>`.

**Comment by Chadori** [comment]
As recommended by a supporter, and Ashley on a related topic. The right choice would be to leave it be.
I planned to add a config addon, but thinking about it, some addons in the collection does support encryption and there's no way of knowing if some users might also use external encryption.

To be on the safe side with any regulations, it's best that the users see this warning. 
You will then be prompted to manually toggle the compliance information, so you should be fine.

You could also add the config tag above, to automate with Cordova.

I hope that helped. 
This is a false alarm of mine, apologies.

**Comment by SalmanShhh** [comment]
for the config tag, do i add it after exporting as xcode project or exported as a cordova project in C3?

**Comment by Chadori** [comment]
> exported as a cordova project in C3

This one should be fine.

**Comment by SalmanShhh** [comment]
so its not possible via xcode export?

**Comment by Chadori** [comment]
> so its not possible via xcode export?

No, it needs to be added, pre-config. 
Why not toggle the compliance prompt instead?

![image](https://user-images.githubusercontent.com/31282960/78390803-c59dcd00-7617-11ea-8b2e-530f9179613f.png)
