### ISSUE TITLE
Firebase Rooms Not Working on c3 Runtime

### ISSUE THREAD

**Issue by colepatters** [Chadori/construct-master-collection#237]
## Request Type
This is a **Bug Report**.

## Describe the bug
While using the c2 runtime, Rooms works correctly and creates a room, but on the c3 runtime when attempting to create a room, it doesn't work properly

## Reproducible .c3p or .capx
[Trivia Game HOST.zip](https://github.com/Chadori/Construct-Master-Collection/files/4428338/Trivia.Game.HOST.zip)

## Steps to Reproduce
1. Open Project
2. Run Lobby Layout

## Screenshots
![image](https://user-images.githubusercontent.com/29346723/78378138-2b497500-7596-11ea-9d2e-fc3f755c062a.png)

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
r193

 ## Construct 2 Version
n/a

**Comment by Chadori** [comment]
**Firebase Rooms :: 2.1.0.2** - Fixed a method reference error.

-----

Thanks again for reporting, I am glad to be able to fix uncaught bugs from the Firebase addons.

Although, perhaps the new and more feature-packed **PlayFab Master Collection** would interest you instead? It has more game features and easier to use than Firebase. It would save you a lot of time.

**It comes free with the Firebase addons.** So, you can find it in your package too.

Here is the documentation: https://www.constructcollection.com/construct-playfab-intro

-----

**Fixed**, now closed.

**Comment by Chadori** [comment]
The release should be available on **10.0**, but in the meantime, you can get the update from the [Discord Community](https://discordapp.com/invite/eS3HK88), in the `#next-release` channel.

**Comment by Chadori** [comment]
**Fixed** a few method reference errors. `Part #2` continuation fix.
