### ISSUE TITLE
Firebase Storage Plugin not working in c3 runtime

### ISSUE THREAD

**Issue by colepatters** [Chadori/construct-master-collection#253]
## Request Type
This is a **Bug Report**.

## Describe the bug
Firebase Storage Plugin works in C2 runtime but not C3 Runtime. When in C3 runtime, using Upload actions create console errors.

## Reproducible .c3p or .capx
[project file.zip](https://github.com/Chadori/Construct-Master-Collection/files/4561007/project.file.zip)

## Steps to Reproduce
1. run default open layout
2. action will run on start of layout
3. error will show up in the console

## Expected behavior
I expected the action to upload the layout capture to the firebase storage

## Screenshots
![image](https://user-images.githubusercontent.com/29346723/80756836-d4817d80-8af8-11ea-9efe-8174252dac4e.png)

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
r197.2 stable

 ## Construct 2 Version
n/a

## Additional Info
none

**Comment by Chadori** [comment]
Thanks for reporting. I will fix it as soon as possible.

**Comment by Chadori** [comment]
Fixed on the version **Storage :: 2.1.0.2**.
Thank you again for reporting.

The update should be available in the `next-release` channel from the [Discord Community](https://discordapp.com/invite/eS3HK88) until the next version is published.
Now closed.

**Comment by Chadori** [comment]
Follow-up fix, a mild rewrite of the **Firebase - Storage** addon. New version is **2.2.0.2**.
**Implemented and Fixed**, now closed.
