### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by OneRepCloser** [Chadori/construct-master-collection#314]
## Request Type
This is a Compile Bug Report.

## Describe the bug
Updated to new addons, attempted to export my main project with advanced minification using the android studio project method. Failed. Made new project and added in the playfab collection of addons (updated to newest versions). Added in an event for each of these addons and then exported the project using the same methods (android studio project - advanced minification). Still Failed. Can you attempt to export this project?

## Reproducible .c3p or .capx
[TestPlayfabAddonsv210.2.zip](https://github.com/Chadori/Construct-Master-Collection/files/5212254/TestPlayfabAddonsv210.2.zip)
[TestPlayFabAddonsV215.zip](https://github.com/Chadori/Construct-Master-Collection/files/5212255/TestPlayFabAddonsV215.zip)

## Steps to Reproduce
1. Open project provided
2. Export project (android studio project - advanced minification)

## Expected behavior
Successful export of android studio project file.

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
v210.2 (Stable) & v215 (Latest Beta)

## Additional Info
minifyWorker.js:2 [Minify] Closure Compiler had 7 compile errors:  Array(7)0: {file: "Input_0", description: "variable _index is undeclared", type: "JSC_UNDEFINED_VARIABLE", lineNo: 9564, charNo: 65}1: {file: "Input_0", description: "variable debugCommonLog is undeclared", type: "JSC_UNDEFINED_VARIABLE", lineNo: 11228, charNo: 7}2: {file: "Input_0", description: "variable C3 is undeclared", type: "JSC_UNDEFINED_VARIABLE", lineNo: 12346, charNo: 4}3: {file: "Input_0", description: "variable Call is undeclared", type: "JSC_UNDEFINED_VARIABLE", lineNo: 13254, charNo: 6}4: {file: "Input_0", description: "variable _obj is undeclared", type: "JSC_UNDEFINED_VARIABLE", lineNo: 13591, charNo: 15}5: {file: "Input_0", description: "variable _subGroup is undeclared", type: "JSC_UNDEFINED_VARIABLE", lineNo: 13604, charNo: 15}6: {file: "Input_0", description: "variable rgba is undeclared", type: "JSC_UNDEFINED_VARIABLE", lineNo: 21720, charNo: 17}length: 7__proto__: Array(0)
self.JobHandlers.minify @ minifyWorker.js:2
main.js:2069 Error exporting:  Exception in job handler: Error: closure compiler error
Hdb @ main.js:2069

**Comment by Chadori** [comment]
I can reproduce, but I'm not sure which addon nor if it's from one of the addons.

**Comment by OneRepCloser** [comment]
Should I attempt to trim it more? If so, any suggestions? I can try different combinations if that helps, I assume we want to narrow it down to 1 or a few plugins (assuming they don't all produce an error).

**Comment by OneRepCloser** [comment]
[TestPlayFabAddonsOnlyPlayFabAPIAddon.zip](https://github.com/Chadori/Construct-Master-Collection/files/5212446/TestPlayFabAddonsOnlyPlayFabAPIAddon.zip)

Empty Project with nothing added but the Playfab Api Addon: 

Export Method:

Android Studio Project Advanced Minification

Error Report (Less errors this time):

minifyWorker.js:2 [Minify] Closure Compiler had 3 compile errors:  Array(3)
self.JobHandlers.minify @ minifyWorker.js:2
main.js:2059 Error exporting:  Exception in job handler: Error: closure compiler error
Pcb @ main.js:2059

Result: 

Failed.

**Comment by Chadori** [comment]
Is it the only addon causing an error?

**Comment by OneRepCloser** [comment]
I can look through them all if necessary.

**Comment by OneRepCloser** [comment]
Tested each of these addons individually in empty projects, some of these aren't necessarily in the playfab addon group so my assumption is that there could be more in the error list from the other addons.

Errors:

- PlayFabAPI
- PlayerManager
- TitleManager
- UserData
- VirtualCurrencies
- MobileFacebook
- MobileGooglePlus
- PhotonRealtime
- Global
- Blank sprite with bounded drag drop behavior
- Blank sprite with AI behavior
- Blank sprite with AI behavior behavior
- Clock

Success:

- AccountInfo
- AccountManager
- Analytics
- CDN
- FriendManager
- Leaderboards
- Publisher
- RealCurrencies
- Authentication
- SyncManager
- CloudScript
- PhotonChat

Never finished exporting:

- MobileInfo (7+ hours, still minifiying) (Haven't reached this issue until now because it would fail, due to the other addons).

**Comment by Chadori** [comment]
This looks bad.
Thanks, I will check it out soon.

**Comment by Chadori** [comment]
Now completely resolved in https://github.com/Chadori/Construct-Master-Collection/issues/348.
Should be out in the next release. Thank you.
