### ISSUE TITLE
Please add MyTarget adapter for the IronSource addon

### ISSUE THREAD

**Issue by dop2000** [Chadori/construct-master-collection#326]
## Request Type
Feature Request

## Information
Please add MyTarget Ads adapter for the IronSource addon

## Feature Demo
Support for MyTarget Ads.

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

**Comment by Chadori** [comment]
Hi, is this still necessary? 
It seems there are better ad-networks to support, like `Smaato`.

Let me know if there is any good reason to support this, otherwise I'm afraid I'll have to close this.
Thank you.

**Comment by dop2000** [comment]
Hi, I'll check with the publisher if they still need this.

**Comment by Chadori** [comment]
Refer to https://github.com/Chadori/Construct-Master-Collection/issues/457 for the new addition.
