### ISSUE TITLE
Mobile Dialog - wrong buttons order on Android

### ISSUE THREAD

**Issue by dop2000** [Chadori/construct-master-collection#327]
## Request Type
This is a **Bug Report**.

## Describe the bug
With 3 or more buttons, the order of buttons is wrong on Android.
In the below example the buttons are shown in this order: 3-1-2 or 2-1-3
It seems to work correctly on iOS

## Reproducible .c3p or .capx
(Edited) **[Link removed]**, 
**Warning**: Please do not bundle addons from the collection.

## Expected behavior
Correct order

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
2.18

**Comment by Chadori** [comment]
**Please, do not bundle addons from the collection in your uploaded test projects.**
This is against the terms and conditions. Thank you.

**Comment by Chadori** [comment]
Are you using the version from the latest collection's release or the one in `#next-release`?
Could you specify the **Mobile Dialog** version that you are using. Thank you.

**Comment by dop2000** [comment]
Sorry about the bundled plugin, I removed it.
Plugin version I'm using is 1.0.1.2

Also, this is not an urgent request, I'm just reporting a bug I noticed.

**Comment by Chadori** [comment]
I'll take note.
You might want to use the latest beta of the [Mobile Dialog (1.1.1.2)](https://github.com/Chadori/Construct-Master-Collection/milestone/29?closed=1) in the `#next-release` channel from the [Discord Community](https://discordapp.com/invite/eS3HK88).
Although, I'm not sure if that will fix your issue. In any case, I made lots of improvements and fixes there that is worth updating to.

**Comment by Chadori** [comment]
I'll take note.
You might want to use the latest beta of the [Mobile Dialog (1.1.1.2)](https://github.com/Chadori/Construct-Master-Collection/milestone/29?closed=1) in the `#next-release` channel from the [Discord Community](https://discordapp.com/invite/eS3HK88).
Although, I'm not sure if that will fix your issue. In any case, I made lots of improvements and fixes there that are worth updating to.

**Comment by Chadori** [comment]
After rewriting the plugin in https://github.com/Chadori/Construct-Master-Collection/issues/563, I can now confirm that this is actually by design.

I could make the plugin reorganize this automatically to an ascending order. However, that could also lead to possible confusions if the Construct plugin does not match the functionality of the Cordova plugin. 
For example, if users try to call the Cordova plugin or Android SDK instead in the future. It could possibly become an additional migration hassle.

I hope you understand.

**Comment by Chadori** [comment]
I'll just note in the documentation instead. 
Thank you for reporting.
