### ISSUE TITLE
Mobile Dialog - suggestions

### ISSUE THREAD

**Issue by dop2000** [Chadori/construct-master-collection#328]
## Request Type
**Suggestion for improvement**

## Information

1. Is it possible to add clickable links to the dialog text? 
Example:

![example](https://i.stack.imgur.com/qM0C8.png)

2. Could you change the delimiter for buttons? Comma is not a good choice, because it can often be used in button text, for example:
"Yes, please"
"No, thank you"
Semicolon will be better suited as a separator.

**Comment by Chadori** [comment]
Hello, thank you for the suggestions.
I'm afraid the first one is not possible yet, Cordova's dialogs plugin doesn't currently allow for that kind of implementation.

For the second one, sure, I'll make a release that will allow you to change the separator key.

**Comment by Chadori** [comment]
Ability to specify a custom button list separator is now available in the `Mobile Dialog :: 1.1.2.2`.
