### ISSUE TITLE
Xcode failed to build project when we use admob

### ISSUE THREAD

**Issue by karimlahbach** [Chadori/construct-master-collection#333]
## Request Type
This is a **Bug Report**.

## Describe the bug
when you use admob from ironsource mediation and export the project to xcode
xcode failed to build the project and give you this error
framework not found UserMessagingPlatform.xcframework

## Reproducible .c3p or .capx
no need just add admob plugin to any project and export

## Steps to Reproduce
1. open empty project and add admob
2. add your app id
3. export to ios ( xcode project)
4. open the project in xcode

## Expected behavior
xcode build the project

## Construct 3 Version 
 **The Construct 3 Version**
the last beta and the stable

**Comment by Chadori** [comment]
This is a Construct 3 issue.

**Comment by Chadori** [comment]
We seem to have a different cause: https://github.com/Chadori/Construct-Master-Collection/issues/332
