### ISSUE TITLE
Unsupported version of Admob adapter in new version of IronSource

### ISSUE THREAD

**Issue by dop2000** [Chadori/construct-master-collection#342]
## Request Type
This is a **Bug Report**.

## Describe the bug
We received the following letter from IronSource support:

![image](https://user-images.githubusercontent.com/36763350/100335608-48e9b400-3029-11eb-9c67-213b238c7aa2.png)

Since it's in a live game with lots of downloads, we are losing revenue. Please provide a solution.

**Comment by Chadori** [comment]
Hi,
I understand how important this is to you, but this isn't a bug. I simply cannot do anything as this version is based on Construct 3's standards.
If I fail to follow their version, Construct 3 objects won't build properly.

**Comment by dop2000** [comment]
As I understand, the previous version of Admob adapter didn't have this problem. 
Can we revert to chadori-mobile-ironsource-admob@0.0.3 ?

**Comment by Chadori** [comment]
I don't think so, since it's a breaking change, but feel free to try, just in case.

Construct 3 and its objects always use the latest version, and I cannot justify changing one plugin's version to break compatibility with other working plugins. 
I think IronSource should instead update their SDK.

Since this is urgent, we can have you made a personalized build, although you'd have to [contact support](support@constructcollection.com).

**Comment by dop2000** [comment]
Basically, now Admob network doesn't work in IronSource. From a customer point of view, this is a bug..

Could you please explain in technical terms why you can't use google-play-services 19.4.0 ? We will have to forward this explanation to IronSource support.

Edit: I tried building with chadori-mobile-ironsource-admob@0.0.3, but I guess it only makes the matter worse. 
It downgrades Admob adapter version, not the Google SDK version, which is still 19.5.0

**Comment by Chadori** [comment]
Construct 3 and the entire Construct Master Collection, are using the latest Play Services version.
IronSource is currently using an older version. 
The entire collection is following Construct 3's standard in versioning, to sync all plugin versions and prevent incompatibilities.
Hence, preventing build failures. Therefore, this is not a bug.

When updating the collection I am thinking about all the users and all the addons in the collection, and its support for Construct 3.
I cannot update one plugin and break the entire collection.

Instead, I recommend waiting for the SDK to update to the latest version. 
Or, as I've previously mentioned, making your own personalized build with the older version without affecting the entire collection. If you are not able to, feel free to [contact support](https://github.com/Chadori/Construct-Master-Collection/issues/support@constructcollection.com).

**Comment by Chadori** [comment]
Closed, since there's no way to resolve this through a conventional update.
I hope you understand.

Thank you.

**Comment by dop2000** [comment]
> 
> 
> Construct 3 and the entire Construct Master Collection, are using the latest Play Services version.
> IronSource is currently using an older version.
> The entire collection is following Construct 3's standard in versioning, to sync all plugin versions and prevent incompatibilities.
> Hence, preventing build failures. Therefore, this is not a bug.
> 
> When updating the collection I am thinking about all the users and all the addons in the collection, and its support for Construct 3.
> I cannot update one plugin and break the entire collection.
> 
> Instead, I recommend waiting for the SDK to update to the latest version.

Thanks, I will relay this information to IS support, hopefully they upgrade the adapter.

We don't want to make yet another personalized plugin build, as this will cause up many potential problems in the future.

**Comment by Chadori** [comment]
Hi,
I tried to ask the Construct Team (Ashley), if I could workaround this.
However, as advised by them, it seems updating the SDK would be a preferable option.

([Reference](https://www.construct.net/en/forum/construct-3/plugin-sdk-10/play-services-version-156831#forumPost1028803))
> I don't think this will work. If plugin A requires version A, and plugin B requires version B, it's not possible to satisfy both requirements. A better solution is to update plugins to work with the latest version.

I will be glad to update the collection if IronSource provided an updated SDK.

**Comment by dop2000** [comment]
Hi,
Thanks for confirming this!
We've asked IS support, they said they are planning to update the Admob adapter in about 2 weeks time. I'll let you know.
