### ISSUE TITLE
GFX - view is misplaced after changing layouts

### ISSUE THREAD

**Issue by dop2000** [Chadori/construct-master-collection#343]
## Request Type
This is a **Bug Report**.

## Describe the bug
This is the first time I am using thins plugin. Maybe I'm doing something wrong?

After switching to another layout the image on the screen is misplaced. 
The lower is the quality setting, the bigger is the displacement.

## Reproducible .c3p or .capx
https://www.dropbox.com/s/uc1422wkpe3v9ry/GFX_Bug_Manual.c3p?dl=0

## Steps to Reproduce
1. Set low quality, for example 30%
2. Press SWITCH LAYOUT button

## Screenshots

![image](https://user-images.githubusercontent.com/36763350/100754215-e9334480-343e-11eb-8027-e493e297a1d9.png)

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
r225

**Comment by dop2000** [comment]
Hi, Could you please advise if this will be fixed soon?
Or is there a workaround, or maybe an older version of the plugin that works?

**Comment by Chadori** [comment]
I'm afraid this bug is dependent on the bug reports I've filed for Construct 3. The new addon has been ready to release for a long time now, but changes depending if a bug report is approved for fixing.
I cannot guarantee when it can work again until Construct 3's side is fixed.

**Comment by Chadori** [comment]
Now fixed in `2.1.0.0`
