### ISSUE TITLE
Mobile Facebook - Add a separate build for IronSource, with aligned versions

### ISSUE THREAD

**Issue by Chadori** [Chadori/construct-master-collection#350]
## Request Type
**Feature Request**

## Information
Mobile Facebook - Add a separate addon build for IronSource, to align their versions.

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 2
 - Construct 3

## Additional Info
This is to be the main addon after the `chadori-mobile-facebook` is whitelisted by the **Construct 3 Team**, for the Construct 3 Build Service.

**Comment by Chadori** [comment]
Also changed the default addon Android version to `7.0.1`, which is aligned with IronSource, as well.

**Comment by Chadori** [comment]
Now completely implemented.

**Comment by baksarbed** [comment]
I have the same error I changed IronSource to 7.0.1
% pod install                                                                 
Analyzing dependencies
Downloading dependencies
Installing FBAudienceNetwork (6.4.1)
Installing FBSDKCoreKit (9.3.0)
Installing Google-Mobile-Ads-SDK (8.13.0)
Installing GoogleAppMeasurement (8.11.0)
Installing GoogleMobileAdsMediationFacebook (6.4.1.0)
Installing GoogleMobileAdsMediationIronSource (7.0.0.0)
Installing GoogleMobileAdsMediationTestSuite (2.0.0)
Installing GoogleUserMessagingPlatform (2.0.0)
Installing GoogleUtilities (7.7.0)
Installing IronSourceSDK (7.0.0.0)

[!] Error installing IronSourceSDK
[!] /usr/bin/curl -f -L -o /var/folders/xk/fvjqt06n2cv7bjcrxs83_7h40000gn/T/d20220201-41834-tpu643/file.zip https://dl.bintray.com/ironsource-mobile/ios-sdk/IronSource7.0.0.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.2 cocoapods-downloader/1.5.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   166    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 502
Warning: Problem : HTTP error. Will retry in 1 seconds. 2 retries left.
  0   166    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 502
Warning: Problem : HTTP error. Will retry in 2 seconds. 1 retries left.
  0   166    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 502

**Comment by Chadori** [comment]
@baksarbed Please stop spamming, and as mentioned in: https://github.com/Chadori/Construct-Master-Collection/issues/341#issuecomment-1026890897
```
@baksarbed, it is clear that your errors are not the same. This is already long fixed with a different Construct 3 plugin replacement already been made long after.
Please refrain from commenting on old issues, if you need support please visit the support channels.

However, it does not look like you are even using our plugin, we do not use that kind of versioning.
```
