### ISSUE TITLE
PlayFab Get User Data Error in Version 11

### ISSUE THREAD

**Issue by rhg1968** [Chadori/construct-master-collection#354]
## Request Type
This is a **Bug Report**.

## Describe the bug
I updated to version 11 and didn't have an issue before, but now when after login is successful with a custom id the command fires to get all user data and I get the following error and the success trigger for get user data never happens:
Exception in 'cv-playfab-userdata' handler 'get-user-data': ReferenceError: e is not defined

## Reproducible .c3p or .capx
_Insert the project file here._

## Steps to Reproduce
1. Login with custom id and it is successful
2. Then issue the User Data function Get all user data
3. Then I get the error in the console and success trigger not fired: Exception in 'cv-playfab-userdata' handler 'get-user-data': ReferenceError: e is not defined
4. 

## Expected behavior
The error wouldn't occur and the success trigger would fire .

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
 **R229**

 ## Construct 2 Version
 **The Construct 2 Version**

**Comment by Chadori** [comment]
Please include a reproducible project next time.
Now fixed, thank you.
The patch release should be in the [#next-release](https://discordapp.com/invite/eS3HK88) channel, from the Discord Community.
