### ISSUE TITLE
Photon does not work with javascript type Module

### ISSUE THREAD

**Issue by fredriksthlm** [Chadori/construct-master-collection#355]
## Request Type
This is a **Bug Report**.

## Describe the bug
When the Photon plugin is used in my project I still cannot use Script type: Module. Only Classic. Even with the latest plugin. 

## Reproducible .c3p or .capx
_Insert the project file here._

## Steps to Reproduce
1. Create a new Construct project (v r229 beta)
2. Include Photon plugin (v 2.0.3.5)
3. Press Preview Project

## Expected behavior
Run without any error.

When I have Script type: Classic it runs fine.

When script type: Module I get the following error in the console:

_Uncaught (in promise) TypeError: Cannot read property 'ConnectionProtocol' of undefined
    at new Photon_Instance (ca5d18dd-0ec3-4bd9-922b-f49a0647d9c3:24)
    at Function.New (jsutil.js:9)
    at Instance._CreateSdkInstance (instance.js:7)
    at ObjectClass._CreateSingleGlobalInstance (objectClass.js:12)
    at new ObjectClass (objectClass.js:7)
    at Function.New (jsutil.js:9)
    at Function.Create (objectClass.js:7)
    at C3Runtime._LoadDataJson (runtime.js:26)
    at C3Runtime.Init (runtime.js:20)
    at async RuntimeInterface._InitDOM (domSide.js:24)_

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
 **The Construct 3 Version**

**Comment by fredriksthlm** [comment]
This issue also occur for **Photon Chat**.

Reproduce:
Create a new project, include the Photon Chat (or Photon Realtime) plugin and press preview: Project cannot load, error occur in console.

(When switching to Classic instead of Module it works fine.)

**Comment by Chadori** [comment]
Hi, both of the addons work fine now in `Construct 3 r232`.
I think it was either a bug in Construct 3 that was fixed, or Construct 3 made a workaround to fix the issue.

Feel free to reply here again if you still get any problems related to this issue.
Thank you.
