### ISSUE TITLE
Issue with the new Leaderboard plugin

### ISSUE THREAD

**Issue by fredriksthlm** [Chadori/construct-master-collection#356]
## Request Type
This is a **Bug Report**.

## Describe the bug
When getting leaderboard data and using tag, the tag doesnt seem to work in the newest login version. Works fine in the previous version.

## Steps to Reproduce
1. Use Get Leaderboard action, use a tag for it.
2. Use On Get Leaderboard : Succeeded, and system condition to verify the Leaderboard.tag to verify when the data is fetched.

## Expected behavior
The event should trigger, when there is a seccessful _Get_.

(it works fine with Leaderboard plugin v 5.5.4.9  but not in 6.5.4.9)

I can see in the console that it worked fine:

_Get Leaderboard :: Positive Response Received : 
{code: 200, status: "OK", data: {…}, CallBackTimeMS: 209, Request: {…}, …}
Triggered : On Get Leaderboard_

## Screenshots

![image](https://user-images.githubusercontent.com/76128871/102402956-d5164800-3fe5-11eb-8d37-f29cb3c35fc2.png)

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
r229

## Additional Info

**Note**! I can see in the console that the fetching of the data works perfectly fine also with the new plugin! I can also see that there are a Successful Get for it (" Triggered : On Get Leaderboard"). When I use the debug. So there is no error with that. But when using the _tag_ in the second event I don't get the event to trigger, but with the previous version of the plugin it worked fine.

**Comment by Chadori** [comment]
Sorry it took a while.
Now fixed with `Leaderboards@6.5.4.10`.

**Comment by Chadori** [comment]
Should be available in the [#next-release](https://discordapp.com/invite/eS3HK88) channel.
