### ISSUE TITLE
get inventory item custom data

### ISSUE THREAD

**Issue by xangetor** [Chadori/construct-master-collection#359]
## Request Type
**Feature Request**

## Information
Express the description of the request.
when i choose get inventory items i get the instances of the item custom data 
## Feature Demo
Express the features you want to happen.
i want to get the custom data of my inventory items
## Construct Editor

 - Construct 3

## Construct Runtime

 - Construct 3

**Comment by Chadori** [comment]
Hi, express orders are handled through `support@constructcollection.com`, for rushed features.
However, I think this update doesn't need paid services, it will be available in the next update.

**Comment by Chadori** [comment]
Removed the `Express order` note.

**Comment by xangetor** [comment]
how do i remove the express note ?

**Comment by Chadori** [comment]
I've already removed it for you.

**Comment by Chadori** [comment]
Implemented in the new version: `VirtualCurrencies@5.1.1.5`.
You can get the new version in the [#next-release](https://discordapp.com/invite/eS3HK88) channel.

**Comment by Chadori** [comment]
(Note: Didn't update the website ACEs screenshots.)

**Comment by Chadori** [comment]
### Virtual Currencies - Item Custom Data

**Features:**
- Custom Data
- Get Custom Data (Key)

**Available expressions:**
- Get User Inventory
- Purchase Item
- Redeem Coupon

**New version**: `VirtualCurrencies@5.1.1.5`

**Comment by Chadori** [comment]
Now closed.
