### ISSUE TITLE
12.0. Construct 3 / Photon - Failed to load all engine scripts

### ISSUE THREAD

**Issue by l-t-m-f** [Chadori/construct-master-collection#394]
Hello!

Since the last update from Scirra my game which uses the Photon plugin does not launch past r225.

I get an error message saying:

Failed to load all engine scripts
in worker : TypeError: Cannot use 'in' operator to search for 'Object' in undefined

Same project works perfectly in r225.

Thank you !!

**Comment by Chadori** [comment]
Hi,
I'm aware of this issue, however this seems to be coming from the c3runtime.
It works on preview, desktop, etc. 
It seems to only affect mobile, which isn't within our control, usually if it works on one platform it should also work on all others. Although, I'm not sure how to report this issue to the Construct Team as well. 

I'll update here if I get any progress. In the meantime, I recommend using the older Construct 3 versions if exporting for mobile.

**Comment by l-t-m-f** [comment]
Hey Chadori, strange... I'm experiencing this on Desktop. Will investigate and provide a more detailed report soon.

**Comment by Chadori** [comment]
Workaround implemented.
Now fixed.

**Comment by Chadori** [comment]
The Photon SDK has been updated.
The addon will also append the new SDK changes, to ensure compatibility.
https://github.com/Chadori/Construct-Master-Collection/issues/405

**Comment by Chadori** [comment]
Latest Photon SDK changes, now included.
