### ISSUE TITLE
Mobile Toast crashes

### ISSUE THREAD

**Issue by fredriksthlm** [Chadori/construct-master-collection#402]
## Request Type
This is a Bug Report.

## Describe the bug
When showing a toast the app crashes instantly.'

## Reproducible .c3p or .capx

[toast.zip](https://github.com/Chadori/Construct-Master-Collection/files/5978376/toast.zip)

change ZIP to c3p  !!!

## Steps to Reproduce
1. save the project as Signed APK
2. Load the project on your phone, and press the toast button
3. it crashes instantly

## Expected behavior
A toast should show up

## Screenshots
![toast](https://user-images.githubusercontent.com/76128871/107887124-1c488880-6f04-11eb-942e-4a701d332a5f.PNG)

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
235

## Additional Info
Samsung Galaxy10 with Android 11

Latest version of Toast plugin
Latest version of Construct3
Latest WebView
Latest Android os

**Comment by Chadori** [comment]
Thank you for reporting.
Construct 3 updated to Android 11 that removed the custom toast feature.
However, there are new alternatives made by Android, which Cordova is still adjusting to.

This is a 3rd party issue, so we cannot do anything about it but wait.

**Comment by Chadori** [comment]
A web alternative is on its way.

**Comment by Chadori** [comment]
I will restore back the Mobile Toast soon in the next update. 
A web alternative doesn't seem as a necessary feature on Desktop and Web, hence will be removed and the native mobile one will be fixed.

**Comment by Chadori** [comment]
Now fixed, thank you.
