### ISSUE TITLE
Mobile Consent - Consent API for the Mobile IronSource Collection and Google Admob Collection

### ISSUE THREAD

**Issue by Chadori** [Chadori/construct-master-collection#446]
## Request Type
**Feature Request**

## Information
**Mobile Consent** - Consent API for the [Mobile IronSource Collection](https://www.constructcollection.com/intro-to-mobile-ironsource) and [Google Admob Collection](https://github.com/Chadori/Construct-Master-Collection/issues/116).

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

**Comment by eltonnobrega** [comment]
Mobile Ads Collection is using "cordova-plugin-admob-free". Should use admob-plus-cordova which is newer. It would also be nice to update the mediation plugins to the latest sdk. No examples are running.

The "Mobile IronSource (Regulation Compliance).c3p" file in Mobile IronSource Collection is not bare because the "Pangle Ads" plugin no longer exists

**Comment by Chadori** [comment]
Hi @eltonnobrega, wrong place to put this, please refer this to customer support channels.

The Mobile Ads Collection was already deprecated, replaced with the [Mobile IronSource Collection](https://www.constructcollection.com/intro-to-mobile-ironsource). The replacement you are asking for is already in the [feature request](https://github.com/Chadori/Construct-Master-Collection/projects/1) list.

> The "Mobile IronSource (Regulation Compliance).c3p" file in Mobile IronSource Collection is not bare because the "Pangle Ads" plugin no longer exists

The Pangle Ads still exist, it is just named [TikTok ads](https://www.constructcollection.com/construct-ironsource-pangle).

Locking, please refer to customer support channels since this thread is for keeping records of changes in the collection.

**Comment by Chadori** [comment]
Click here for the [support channels](https://www.constructcollection.com/support). I recommend the [Discord server](https://discord.com/invite/eS3HK88) for questions.

**Comment by Chadori** [comment]
New [Mobile Consent](https://www.constructcollection.com/documentations/mobile/mobile-consent) plugin with version `1.0.0.0`, for both the [Mobile IronSource Collection](https://www.constructcollection.com/tutorials/ironsource/introduction) and [Google Admob Collection](https://www.constructcollection.com/tutorials/admob/introduction).
