### ISSUE TITLE
[Mobile OneSignal] Update Cordova plugin version to '2.11.4'

### ISSUE THREAD

**Issue by Chadori** [Chadori/construct-master-collection#498]
## Request Type
**Feature Request**

## Information
[Mobile OneSignal] Update Cordova plugin version to `2.11.4`.

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

**Comment by Boulerzzz** [comment]
We will need 3.0.1 or above now to support android 12.

**Comment by Chadori** [comment]
Here's the new one: https://github.com/Chadori/Construct-Master-Collection/issues/561

**Comment by Boulerzzz** [comment]
Yeah I saw you had opened a new issue for that right after I posted here!

**Comment by Chadori** [comment]
Implemented and now completed here: https://github.com/Chadori/Construct-Master-Collection/issues/561
