### ISSUE TITLE
[Mobile IronSource Collection] Update all advertisement SDKs to '7.2.1.1'

### ISSUE THREAD

**Issue by natebluewizard** [Chadori/construct-master-collection#504]
## Request Type
**Feature Request**

## Information
[Mobile IronSource Collection] Update all advertisement SDKs, including all ad-network mediation networks to 7.2.0, for both Android and iOS.

Not sure what cordova version is required... 

chadori-mobile-ironsource
chadori-mobile-ironsource-debug
chadori-mobile-ironsource-adcolony
chadori-mobile-ironsource-admob
chadori-mobile-ironsource-applovin
chadori-mobile-ironsource-chartboost
chadori-mobile-ironsource-facebook
chadori-mobile-ironsource-fyber
chadori-mobile-ironsource-hyprmx
chadori-mobile-ironsource-inmobi
chadori-mobile-ironsource-maio
chadori-mobile-ironsource-mytarget
chadori-mobile-ironsource-pangle
chadori-mobile-ironsource-smaato
chadori-mobile-ironsource-snap
chadori-mobile-ironsource-tapjoy
chadori-mobile-ironsource-tencent
chadori-mobile-ironsource-unityads
chadori-mobile-ironsource-vungle

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

**Comment by Chadori** [comment]
IronSource and ad-network adapter SDKs' update queue set for newly launched `7.2.1`.

**Comment by Chadori** [comment]
Will queue the update for a few more versions. I'm waiting for the next few releases IronSource makes, so that we can consolidate all the additions for the next whitelist request.

**Comment by eltonnobrega** [comment]
Update your Android app setup

Google Play’s updated policies require the advertising ID to be removed for Families apps. These changes will come into effect on April 1.

To make sure your apps stay compliant with Google Play’s Families Policy, complete these steps:

Integrate [ironSource SDK 7.2.1+](https://go.is.com/e/912171/download-ironsource-sdk-/37v88/552638113?h=1rJYCmvC9rvqQg9N6KZnPim0-evgrHFqq9aNMvfTj8k) for Android and Unity

Update each app’s manifest file to prevent access to the Android Advertising ID (AAID) for users on Android 12+:
<uses-permission android:name="com.google.android.gms.permission.AD_ID" tools:node="remove"/> 

Use the ironSource Metadata API to opt out of device data for users on Android 11 and below:
ironSource.SetMetaData(‘IS_DeviceID_OptOut’,’true’)

Update your permissions:
implementation 'com.google.android.gms:play-services-appset:16.0.0'

My app is part of Families apps, I need to do this update.

**Comment by eltonnobrega** [comment]
chadori-mobile-ironsource 0.9.0 only references admobadadapter

**Comment by Chadori** [comment]
Include update with: https://github.com/Chadori/Construct-Master-Collection/issues/520

**Comment by Chadori** [comment]
Testing new implementation for Android 12 and **Google Play Families programs**.

**Comment by Chadori** [comment]
Added new requirement plugin for [Google Play Families programs](https://github.com/Chadori/Construct-Master-Collection/issues/521).

**Comment by Chadori** [comment]
IronSource and ad-network adapter SDKs' update queue set for newly launched `7.2.1.1`.

**Comment by Chadori** [comment]
Replaced previously added requirement plugin to new plugin for [Google Play Families programs](https://github.com/Chadori/Construct-Master-Collection/issues/524).

**Comment by Chadori** [comment]
Finished all the testing of all ad-networks, everything seems to be working fine and well.

However, the latest Google AdMob Android SDK (`20.6.0`) which we are using in `7.2.1.1` can only build in applications targeted for Android 12.
Cordova currently cannot compile for the Android 12, consequently [Construct 3 cannot as well (regression r288)](https://www.construct.net/en/make-games/releases/beta/r288).

Therefore, I'll release **2 build versions**, one plugin with Mobile Ads SDK version `20.4.0` while Cordova and Construct 3 are still targeting to Android 11. And, another plugin for the future with Mobile Ads SDK version `20.6.0`, this is for when Cordova and Construct 3 finally targets to Android 12 builds.

**Comment by Chadori** [comment]
Finished all the testing of all ad-networks, everything seems to be working fine and well.

However, the latest Google AdMob Android SDK (`20.6.0`) which we are using in `7.2.1.1` can only build in projects targeted for Android 12.
Cordova currently cannot compile for the Android 12, consequently [Construct 3 cannot as well (regression r288)](https://www.construct.net/en/make-games/releases/beta/r288).

Therefore, I'll release **2 build versions**, one plugin with Mobile Ads SDK version `20.4.0` while Cordova and Construct 3 are still targeting to Android 11. And, another plugin for the future with Mobile Ads SDK version `20.6.0`, this is for when Cordova and Construct 3 finally targets to Android 12 builds.

**Comment by Chadori** [comment]
Finished all the testing of all ad-networks, everything seems to be working fine and well.

However, the latest Google AdMob Android SDK (`20.6.0`) which we are using in `7.2.1.1` can only build in projects targeted for Android 12.
Cordova currently cannot compile to Android 12, consequently [Construct 3 cannot as well (regression r288)](https://www.construct.net/en/make-games/releases/beta/r288).

Therefore, I'll release **2 build versions**, one plugin with Mobile Ads SDK version `20.4.0` while Cordova and Construct 3 are still targeting to Android 11. And, another plugin for the future with Mobile Ads SDK version `20.6.0`, this is for when Cordova and Construct 3 finally targets to Android 12 builds.

**Comment by Chadori** [comment]
Finished testing iOS as well, and it works fine.

However [there is an issue with Meta Audience Network (Facebook Ads)](https://github.com/Chadori/Construct-Master-Collection/issues/532) currently for iOS, which I expect would be fixed in the next versions.  If you encounter this, please [click here for the workaround](https://github.com/Chadori/Construct-Master-Collection/issues/532).

If the patch update releases, we should be able to update immediately because [we can now update the dependency versions manually with the Construct 3 plugins](https://github.com/Chadori/Construct-Master-Collection/issues/533) through Cordova plugin variables.

Both Android and iOS, in both debug and main plugins, have been tested to work well.

Closing, update should be included in the next release.
Thank you for reporting!

**Comment by Chadori** [comment]
Whitelisting request has been posted.
