### ISSUE TITLE
Firebase Analytics - Android build failed (signed release apk)

### ISSUE THREAD

**Issue by alinj-13** [Chadori/construct-master-collection#507]
## Request Type
This is a **Bug Report**.

## Describe the bug
I can't export signed release apk when the Firebase Analytics plugin is added to the project. I tried your template of Firebase Analytics in Mobile - Release 32 [Patch] and didn't work either. The error text: 

Error: Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=~~/androidSDK (recommended setting)
ANDROID_HOME=~~/androidSDK (DEPRECATED)
Using Android SDK: ~~/androidSDK
:wrapper

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app

> Configure project :app
Adding classpath: com.google.gms:google-services:4.3.8

> Task :app:preBuild UP-TO-DATE
> Task :app:preReleaseBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preReleaseBuild UP-TO-DATE
> Task :CordovaLib:compileReleaseAidl NO-SOURCE
> Task :app:compileReleaseAidl NO-SOURCE
> Task :CordovaLib:packageReleaseRenderscript NO-SOURCE
> Task :app:compileReleaseRenderscript NO-SOURCE
> Task :app:generateReleaseBuildConfig
> Task :app:writeReleaseApplicationId
> Task :app:analyticsRecordingRelease
> Task :app:javaPreCompileRelease
> Task :CordovaLib:writeReleaseAarMetadata
> Task :app:generateReleaseResValues
> Task :app:generateReleaseResources
> Task :app:processReleaseGoogleServices FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https:/~~/command_line_interface.html#sec:command_line_warnings
7 actionable tasks: 7 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it.
Searched Location:
~~/google-services.json
~~/google-services.json
~~/google-services.json
~~/google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https:/~~/help.gradle.org

BUILD FAILED in 1s
Command failed with exit code 1: ~~/gradlew cdvBuildRelease -b ~~/build.gradle

## Reproducible .c3p or .capx
_Insert the project file here._

## Steps to Reproduce
1. 
2. 
3. 
4. 

## Expected behavior
Have the apk successfully exported.

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
r285.3

**Comment by Chadori** [comment]
Hi, thank you for reporting.
I have fixed the plugin and also have updated the SDK versions.

The new version will be in the next release, you can also get the fixed version in the [Discord Community](https://discord.com/invite/eS3HK88) in the `#next-release` channel.

However, I'm afraid the Construct 3 Build Service is still in-progress of whitelisting by the Construct Team, we will have to wait for them.
In the meantime, you should be able to build successfully using the `Cordova Project` export option.

To make it easier for everyone in the future, I've [requested a solution to reduce the whitelisting duration](https://www.construct.net/en/forum/construct-3/plugin-sdk-10/request-specifying-resource-168426). Hopefully if approved, this will make updates quicker in the near future.

**Comment by Chadori** [comment]
New version: `Mobile Firebase Analytics - 4.0.0.0`

The [Mobile Firebase Remote Config](https://www.constructcollection.com/firebase-remote-config) still seems to be working fine, but I will also update it to the latest version with the latest features once I get a response from the request I've made to the Construct Team, since the update depends on that.

**Comment by Chadori** [comment]
[Release 33.0](https://chadori.itch.io/construct-master-collection/devlog/359976/release-330) is now out with the fix.

**Comment by Chadori** [comment]
Amazingly, the Construct Team whitelisted the Cordova plugin immediately.
The fix should now build in the Construct 3 editor.

**Comment by alinj-13** [comment]
Thanks :)
