### ISSUE TITLE
[Mobile Billing] Failed register product with underscore

### ISSUE THREAD

**Issue by anandiamy** [Chadori/construct-master-collection#553]
## Request Type
This is a **Bug Report**.

## Describe the bug
[Mobile Billing] Failed register product with underscore

## Steps to Reproduce
1. Register product with underscore
2. Initialize
3. the error "Failed to register product 'remove_ads' appears.

## Expected behavior
There should be no error, because the product id on the play store console can use an underscore

## Screenshots

![construct remove_ads error](https://user-images.githubusercontent.com/8675936/175842623-2863ac5a-fd8f-495c-9eaf-dfda64c2fa64.png)

![failed to register product](https://user-images.githubusercontent.com/8675936/175842658-cbe80370-9d4b-4b0e-aa00-b1de50efe6c8.png)

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
r293-3

## Additional Info
When I create product id with  no underscore, its worked

**Comment by Chadori** [comment]
Hi, this is not a bug.
**The Mobile Billing supports product identifications with underscores**.

Here is an example in my development test project:

![image](https://user-images.githubusercontent.com/31282960/175844139-b216f90d-384e-4199-8f80-bb4116b5b2be.png)

You have misunderstood the error that was presented to you by Google. The error means you are trying to register a product id that is either inexistent in your Google Developer Console project or is not setup properly.

Perhaps try to start debugging your issue with your account from there.

Good luck.

**Comment by Chadori** [comment]
Hi, this is not a bug.
**The Mobile Billing supports product identifications with underscores**.

Here is an example in my development test project:

![image](https://user-images.githubusercontent.com/31282960/175844139-b216f90d-384e-4199-8f80-bb4116b5b2be.png)

You have misunderstood the error that was presented to you by Google. The error means you are trying to register a product id that is either inexistent in your Google Developer Console project or is not set properly.

Perhaps try to start debugging your issue with your account from there.

Good luck.

**Comment by anandiamy** [comment]
Ok, I will test again

Btw... Your screenshot uses the "Consumable" product not "Non-Cosumable", different from my screenshot above

**Comment by Chadori** [comment]
Consumables are non-consumables that are consumed.
They are the same.
