### ISSUE TITLE
Error when open project demo "Mobile Facebook Auth.c3p"

### ISSUE THREAD

**Issue by anandiamy** [Chadori/construct-master-collection#606]
## Request Type
This is a **Bug Report**.

## Describe the bug
When I open the project "Mobile Facebook Auth.c3p" in "PlayFab Master Collection -> Authenticate -> Documentation" an error appears "Plugin Mobile Facebook (CV_MobileFacebook) by Chadori" as shown below

![image](https://user-images.githubusercontent.com/8675936/216246279-c8d2839b-6fea-49a8-8008-e815ee6086a3.png)

Note : I have installed the add on "Mobile Facebook.c3addon"

## Reproducible .c3p or .capx
[Mobile Facebook Auth.zip](https://github.com/Chadori/Construct-Master-Collection/files/10565663/Mobile.Facebook.Auth.zip)

## Steps to Reproduce
1. Open the project "Mobile Facebook Auth.c3p" in PlayFab Master Collection -> Authenticate -> Documentation

## Expected behavior
It shouldn't show any error since I already installed the addon

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
R327.2

**Comment by Chadori** [comment]
It seems you are using an old legacy plugin for the new plugin's demo project, we are now using the plugin id [Chadori_MobileFacebook](https://www.constructcollection.com/documentations/mobile/mobile-facebook) in the latest versions.
