### ISSUE TITLE
PlayFab Authentication : Inconsistent Triggering

### ISSUE THREAD

**Issue by Chadori** [Chadori/construct-master-collection#8]
## Request Type
This is a **Bug Report**.

## Describe the bug
**Authentication** inconsistent triggering from the **Server Negative Response**.

## Construct Editor
 - Construct 2
 - Construct 3

## Construct Runtime
 - Construct 2
 - Construct 3

 ## Construct 3 Version 
 **The Construct 3 Version**

 ## Construct 2 Version
 **The Construct 2 Version**

## Additional Info
**May affect** all **PlayFab Master Collection** that uses the triggering framework I have designed, named **C3Trigger**.

---

🕒 Archived Report : **December 16, 2018**

**Comment by ChadoriRebornXD** [comment]
🕒 Archive Response :
This bug report is a false alarm, closing!

**Comment by ChadoriRebornXD** [comment]
🕒 Archive Response :
This bug report is a false alarm, closing!

**Comment by Chadori** [comment]
🕒 Archived Response
---
This bug report is a **false alarm**, closing!
