### ISSUE TITLE
Unity Mediation Ad doesn`t work. Maybe more Mediation Plugins affected

### ISSUE THREAD

**Issue by xxhrost** [Chadori/construct-master-collection#91]
## Request Type
This is a **Bug Report**.

## Describe the bug
I implemented the Unity Mediation Plugin in Construct 2. Exporting with phonegap not possible. Phonegap produces error log (Screenshot below). Exporting with just Mobile Master Ad Addon works fine, so also with Admob. Maybe more Mediation Ads are affected. I did everything right in the config.xml (screenshot also below)

## Steps to Reproduce
1. Implement Unity Ad Addon
2. Fill the config.xml
3. Export through phone gap
4. Error Log

## Screenshots
![unknown](https://user-images.githubusercontent.com/53152718/61595710-f5788200-abfa-11e9-98be-27355c38cb75.png)

![unknown2](https://user-images.githubusercontent.com/53152718/61595729-38d2f080-abfb-11e9-9268-36a70c4f6b51.png)

## Construct Editor
 - Construct 2

## Construct Runtime
 - Construct 2
 
 ## Construct 2 Version
Latest

**Comment by QuasarX** [comment]
It is wrong plugin name.
Try this `lycwed-cordova-plugin-admob-unityads`

**Comment by Chadori** [comment]
@QuasarX You are amazing. Thanks.

**Comment by xxhrost** [comment]
i will try right now and will let you know

**Comment by xxhrost** [comment]
it worked!!!
Thank you guys! 
@ChadoriRebornXD can you please fix that bug in the addon itself so we dont have the struggle to change it in the config.xml?

**Comment by Chadori** [comment]
Of course @xxhrost . Thank you again @QuasarX .
Alright, it'll be available on the next release.

**Comment by xxhrost** [comment]
can you check the other Mediation addons aswell? I haven`t created accounts for the other mediations

**Comment by Chadori** [comment]
@xxhrost Alright.

**Fixed**, closing!
