### ISSUE TITLE
Game laggs when preloading Admob Banner or Rewarded Video

### ISSUE THREAD

**Issue by xxhorst2** [Chadori/construct-master-collection#92]
## Request Type
This is a **Bug Report**.

## Describe the bug
Everytime i start preloading Admob Banner or Rewarded Video, the whole game starts lagging and stuttering. When I use Unity Mediation nothing laggs or stutter, everything works fine. This happens only with Admob Ads. Tested with two phones (S7+ and Note 8). What i forgot to mention. The smartphones getting hot when preloading Admob Ads

## Construct Editor
 - Construct 2

## Construct Runtime
 - Construct 2

 ## Construct 2 Version
Latest

**Comment by Chadori** [comment]
Can you try **FacebookxUnity Ads** instead.

**Comment by xxhorst2** [comment]
i dont have a account for Facebook. But i think it doesn`t matter if i add facebok or unity? the problem occurs only when Admob Ads are preloaded. Lets say i dont get a unity fill, then next will be admob ads. I can not deactivate admob ads they will be shown every time when another ad network can not fill

**Comment by Chadori** [comment]
It matters because the mediation plugin might be defective. It's more practical to replace Cordova mediation plugins than fixing them. These are 3rd party mediation plugins after all. This is until I get the time to create my own mediation adapters.

**Comment by xxhorst2** [comment]
sounds good

**Comment by Chadori** [comment]
Please try using the **Facebook x Unity Ads** plugin and see if it works out for you. Thank you.
Besides, **Admob, Facebook and Unity** are the important ad-networks you would want in your app.
