### ISSUE TITLE
The "getDisplayName" in Leaderboard Plugin and "updateDisplayName" in AcountManager Plugin  doesn't work.

### ISSUE THREAD

**Issue by tuzke** [Chadori/construct-master-collection#93]
## Request Type
**Bug Report**.

## Describe the bug
The getDisplayName function doesn't work, I try many ways and still can't update DisplayName in Plugin AcountManager, and I edit them manually, but it seems that the getDisplayName function in the leaderboard plugin doesn't work. I can't get DisplayName. If you have free time please check it out. Thank you!

## Reproducible .c3p or .capx
The sample project.

## Screenshots
![unknown](https://www.upsieutoc.com/images/2019/07/23/wwwwqq.png)

![unknown](https://www.upsieutoc.com/images/2019/07/23/aaq.png)

![unknown](https://www.upsieutoc.com/images/2019/07/23/qqqqq.png)

![unknown](https://www.upsieutoc.com/images/2019/07/23/aaaa.png)

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
Construct 3 Version 159

**Comment by Chadori** [comment]
Thank you.
Will check this out.

**Comment by tuzke** [comment]
When I update display name


![unknown](https://www.upsieutoc.com/images/2019/07/23/sssss.png)

**Comment by Chadori** [comment]
@tuzke Send a reproducible project with steps. Because that error has nothing to do with Display Names, so I need info when I investigate.
Thank you.

**Comment by tuzke** [comment]
Sorry, I can't send the project to you now because I'm not having a computer in the next few days, but try creating a new project and check the update display name function with the Account Manager plugin, you'll see it There is a problem, it will not run. If you can run it, please show me the project that you have done. thank you!

**Comment by Chadori** [comment]
@tuzke I can reproduce. Will make a fix right away.

**Comment by Chadori** [comment]
Just to be clear though, the **Leaderboards** plugin doesn't have any bug. There is no **Display Name** being shown because you've authenticated using the **Custom ID** option which initially has no **Display Name** of the user.

The fault lies on the **Account Manager** plugin where it fails to update the **Display Name** and instead files a **Report Player** action, which failed for obvious reasons.

Anyway, thanks for reporting. It should be on the **Discord Server**'s #next-release in a few minutes.

**Comment by Chadori** [comment]
Hi, sorry, it seems that the **Leaderboards** plugin in fact has a bug, there is also a problem with getting the **PlayFabID**.
 
There are 2 bugs atm:
- **Profile Constraints** : There were a bit confusion on the usage of the **Profile Contraints** but now it will be fixed. **[Entire PlayFab Collection]** ✔️
- **PlayFabID** - Expressions don't return this data properly. **[Leaderboards]** ✔️

These will be fixed asap.

**Comment by Chadori** [comment]
**Implemented**, now closing!
Will be on the next release. Thanks for reporting.

**Comment by Chadori** [comment]
## New Features
**PlayFab API**
- Profile Constraints Mode

## Changes
**Changed Profile Constraints global listing.**
- API Module
- Friend Manager
- Leaderboards
- Player Manager

**Comment by Chadori** [comment]
## Note
**The following addons were also fixed:**
- **Account Manager** - PlayFab Master Collection.
