### ISSUE TITLE
black screen with plugin notification

### ISSUE THREAD

**Issue by gloater** [Chadori/construct-master-collection#94]
## Request Type
This is a **Bug Report**.

## Reproducible .c3p or .capx
_Insert the project file here._
[notifaction.c3p.zip](https://github.com/ChadoriRebornXD/Construct-Master-Collection/files/3424683/notifaction.c3p.zip)

## Steps to Reproduce
1. 
2. 
3. 
4. 

## Construct Editor
 - Construct 2
 - Construct 3

## Construct Runtime
 - Construct 2
 - Construct 3

 ## Construct 3 Version 
 **The Construct 3 Version**

 ## Construct 2 Version
 **The Construct 2 Version**

**Comment by gloater** [comment]
[notifaction.c3p.zip](https://github.com/ChadoriRebornXD/Construct-Master-Collection/files/3422266/notifaction.c3p.zip)

**Comment by Chadori** [comment]
Alright, I will investigate this now.

**Comment by Chadori** [comment]
**Mobile Notifications** isn't supported by the **C3 Build Service** yet, wait until they finish white-listing it.

Although, I tried building this on **PhoneGap** and found out an **SDK** change from **PushWoosh** that makes it fail to build. 

So, will implement that instead and redirect this issue there: https://github.com/ChadoriRebornXD/Construct-Master-Collection/issues/97

**Comment by Chadori** [comment]
**Redirected** issue to : https://github.com/ChadoriRebornXD/Construct-Master-Collection/issues/99
